name: afer
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #icons
  iconly: ^1.0.1
  #Bloc Package
  bloc: ^8.0.1
  flutter_bloc: ^8.0.0
#video player
  flick_video_player: ^0.5.0
  video_player: ^2.4.6
  #prevent screen recording
  flutter_windowmanager: ^0.2.0

  image_picker: ^0.8.5+3
  #Firebase
  firebase_core: ^1.15.0
  firebase_auth: ^3.3.16
  cloud_firestore: ^3.1.13
  firebase_storage: ^10.3.8
  #local storage
  shared_preferences: ^2.0.11

  motion_toast: ^2.3.2
  conditional_builder_null_safety: ^0.0.6
  connection_notifier: ^0.0.1
  easy_localization: ^3.0.1
  #Navigation
  sliding_clipped_nav_bar: ^3.1.0+3
  lottie: ^1.4.2
  barcode_widget: ^2.0.2
  flutter_barcode_scanner: ^2.0.0
#to get pdf from url and show it
  internet_file: ^1.2.0
  pdfx: ^2.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: any

flutter_icons:
  android: true
  ios: true
  image_path: "Asset/Image/AferLogo.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "Asset/Image/iconLogo.png"

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true


  assets:
    - Asset/Image/
    - Asset/translition/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
