name: afer
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  iconly: ^1.0.1
  bloc: ^8.0.1
  flutter_bloc: ^8.0.0
#video player
  flick_video_player: ^0.5.0
  video_player: ^2.4.6
  #prevent screen recording
  flutter_windowmanager: ^0.2.0

  image_picker: ^0.8.5+3
  firebase_core: ^1.15.0
  firebase_auth: ^3.3.16
  cloud_firestore: ^3.1.13
  firebase_storage: ^10.3.8
  shared_preferences: ^2.0.11
  motion_toast: ^2.3.2
  conditional_builder_null_safety: ^0.0.6
  connection_notifier: ^0.0.1
  easy_localization: ^3.0.1
  lottie: ^1.4.2
  barcode_widget: ^2.0.2
  flutter_barcode_scanner: ^2.0.0
#to get pdf from url and show it
  internet_file: ^1.2.0
  pdfx: ^2.2.0
  circular_bottom_navigation: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: any

flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/logo.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/image/logo.png"

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/

  fonts:
    - family: Rajab
      fonts:
        - asset: assets/font/abdo.Rajab.ttf
    - family: Stoor
      fonts:
        - asset: assets/font/ad-STOOR.otf
    - family: AdvertisingExtraBold
      fonts:
        - asset: assets/font/AdvertisingExtraBold-1.ttf
    - family: ABarada Reqa
      fonts:
        - asset: assets/font/barada-reqa.ttf

